apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:secretpassword@mongodb.muchtodo.svc.cluster.local:27017/muchtodo?authSource=admin"